---

- hosts: all
  become: true
  tasks:

          - name: install apache, php and update repository index 
            dnf:
                    name:
                      - httpd
                      - php
                    state: latest
                    update_cache: yes
            when: ansible_distribution == "Rocky"

          - name: permit traffic in default zone for http service
            ansible.posix.firewalld:
                    service: http
                    permanent: yes
                    state: enabled
            when: ansible_distribution == "Rocky"

          - name: permit traffic in default zone for https service
            ansible.posix.firewalld:
                    service: https
                    permanent: yes
                    state: enabled
            when: ansible_distribution == "Rocky"

          - name: Firewalld relaod
            systemd:
                    name: firewalld
                    state: reloaded
            when: ansible_distribution == "Rocky"

          - name: Make sure a service unit is running
            ansible.builtin.systemd:
                    state: started
                    name: httpd
            when: ansible_distribution == "Rocky"


          - name: install apache2, php packages and update repository index
            apt:
                    name:
                      - apache2
                      - libapache2-mod-php
                    state: latest
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"






