---

- hosts: all
  become: true
  pre_tasks:

          - name: install updates (Ubuntu)
            apt:
                    upgrade: dist
                    update_cache: yes
            when: ansible_distribution == "Ubuntu"


          - name: install updates (Rocky)
            dnf:
                    update_only: yes
                    update_cache: yes
            when: ansible_distribution == "Rocky"

- hosts: web_servers
  become: true
  tasks:

          - name: install apache and php for Rocky servers 
            dnf:
                    name:
                      - httpd
                      - php
                    state: latest
            when: ansible_distribution == "Rocky"

          - name: permit traffic in default zone for http service
            ansible.posix.firewalld:
                    service: http
                    permanent: yes
                    state: enabled
            when: ansible_distribution == "Rocky"

          - name: permit traffic in default zone for https service
            ansible.posix.firewalld:
                    service: https
                    permanent: yes
                    state: enabled
            when: ansible_distribution == "Rocky"

          - name: Firewalld relaod
            systemd:
                    name: firewalld
                    state: reloaded
            when: ansible_distribution == "Rocky"

          - name: Make sure a service unit is running
            ansible.builtin.systemd:
                    state: started
                    name: httpd
            when: ansible_distribution == "Rocky"


          - name: install apache2 and php for Ubuntu servers
            apt:
                    name:
                      - apache2
                      - libapache2-mod-php
                    state: latest
            when: ansible_distribution == "Ubuntu"


- hosts: db_servers
  become: true
  tasks:
          
          - name: install mariadb package (Ubuntu)
            apt:
                    name: mariadb-server
                    state: latest
            when: ansible_distribution == "Ubuntu"

          - name: install mariadb package (Rocky)
            dnf:
                    name: mariadb
                    state: latest
            when: ansible_distribution == "Rocky"


- hosts: file_servers
  become: true
  tasks:

          - name: install samba package
            package:
                    name: samba
                    state: latest
